### ISSUE TITLE
Make sure that input file for SERPENT2 build-in simulation is up to date

### ISSUE THREAD

**Issue by andrewryh** [arfc/saltproc-validation#3]
You sent me SERPENT2 input file for SD-TMSR simulation a few weeks ago.
I extracted the geometry description and placed it in:
`saltproc-validation/SD-TMSR/geometry/tmsr_full`

And the input file without geometry in:
`saltproc-validation/SD-TMSR/serpent/tmsr_core`

Obviously, you changed that input when setting up this 2-days-long, 3-min steps simulation.
Please, change this file to the current one (don't forget to keep geometry in the separate file, it is much more convenient).

**This issue can be closed after @osamamala will update `saltproc-validation/SD-TMSR/serpent/tmsr_core`**

**Comment by osamamala** [comment]
I updated the tmsr_core file to SD-TMSR_core file. The geometry file doesn't change. 
Why in the 'arfc/saltproc-validation' fork nothing happened? @andrewryh

**Comment by andrewryh** [comment]
@osamamala 
**arfc/saltproc-validation** is upstream. It will change only after merging PR from osamamala:master to arfc:master.

But we not going do this now. Idea is make changes in your fork until some milestone has been achieved and then create PR to push you changes in main repository (**arfc/saltproc-validation**).

You successfully finish this assignment, now you can close this issue.

**Comment by osamamala** [comment]
thank you very much, now the picture is completed for me,

**Comment by osamamala** [comment]
thank you very much, now the picture is completed for me, @andrewryh
