### ISSUE TITLE
Revision required: Fuel depletion analysis for SD-TMSR Manuscript

### ISSUE THREAD

**Issue by andrewryh** [arfc/saltproc-validation#4]
> Prof. Tikhomirov agrees and proposes to start calculations required for the first paper.

@osamamala I reviewed Abstract, Introduction and sent you my major concerns. Please, revise the whole manuscript carefully and upload it in `saltproc-validation/SD-TMSR/doc/`. Word file is okay but consider in the future use LaTeX format, it is much more convenient for review and is academic standard right now.

After that, we gonna review it carefully on ARFC side. It's not blocking my simulations for initial vs equilibrium composition comparison.

**This issue can be closed when the revised manuscript file will be uploaded in `saltproc-validation/SD-TMSR/doc/`.**

**Comment by andrewryh** [comment]
@osamamala Could you please explain how you chose U233 concentration for initial composition? Tried vary concentrations until obtained Keff close to 1.0?

**Comment by osamamala** [comment]
@andrewryh 
from the following articles,

[10] Nuttin A, Heuer D, Billebaud A, et al. Potential of thorium molten salt reactors: detailed calculations and concept evolution with a view to large scale energy production. Prog. Nucl. Energy. 2005;46(1):77-99.
[21] Li GC, et al. Optimization of Th-U fuel breeding based on a single-fluid double-zone thorium molten salt reactor. Progress in Nuclear Energy. 2018;108:144-151.,

you can see that the general fuel salt composition is LiF-BeF2-(Th/U)F4 at 70-17.5-12.5 mol% respectively, then I changed the concentration of U233 and Th until I obtained the keff ≈ 1.00507 +/- 0.00036. so the concentration which I obtained is  LiF-BeF2-ThF4-233UF4 at 70-17.5-12.3-0.2 mol% and the initial inventory of 233U is 1.31 (t), in the Chinese paper the initial inventory of 233U is 1.27 (t) .

**Comment by andrewryh** [comment]
@osamamala I am almost finished writing of my part of RESULTS section.
Could you please push all your changes in your fork: `osamamala/2019-ashraf-rykhl-sd-tmsr-serpent ` ?
So, I would be able to add my piece and resolve all conflicts before sending it @juliaroessler for proofreading.
Thanks.

**Comment by osamamala** [comment]
@andrewryh 
Great!  
Everything up-to-date

Thanks

**Comment by andrewryh** [comment]
@osamamala Great! Then I gonna put my part in it.
