### ISSUE TITLE
Complimentary simulations for Fuel depletion analysis for SD-TMSR Manuscript

### ISSUE THREAD

**Issue by andrewryh** [arfc/saltproc-validation#5]
So, I gonna make the following simulations for this paper:
- [x] Temperature coefficients of reactivity for initial and equilibrium state (separately calculated Doppler, salt density, graphite density, spectral shift, etc effects). You have an only total coefficient, would be nice to see a contribution from each effect.
- [x] Power and breeding distribution 2D plots (see my Thesis). Would be nice to have it to show the efficiency of 2-region single-fluid design.
- [x] Six factors formula parameters for initial and equilibrium composition.

**Comment by osamamala** [comment]
@andrewryh 
Hello,
The burnup time extended to 60 yrs and the statistical error decreased to 35 pcm, some results uploaded in this link; 
https://github.com/osamamala/saltproc-validation/tree/master/SD-TMSR/doc/plots_60_years_using_SERPENT

for output files, please see;
https://github.com/osamamala/saltproc-validation/tree/master/SD-TMSR/serpent/60-years-analysis

I hope you can start to calculate the temperature coefficients of reactivity, power and breeding distribution, six factors formula parameters as soon as possible while I modify the manuscript with the new results. 
Also, I will send you the reprocessing scheme which I used in this simulation in order to add it in SaltProc so that we will be able to verify the SaltProc against the SERPENT built-in mode in SD-TMSR  in the near future.

best 
Osama

**Comment by andrewryh** [comment]
@osamamala 
Cool, very pretty results, I'm pretty happy with uncertainty you've obtained and special thanks for this plot: https://github.com/osamamala/saltproc-validation/blob/master/SD-TMSR/doc/plots_60_years_using_SERPENT/dm%25.png
This is awesome, you must include it in the manuscript.

Indeed, I can now go ahead and calculate the temperature coefficients of reactivity, power and breeding distribution, six factors formula parameters. Please, send me by email your latest input file (I have a geometry file, but I need a neutron population/active-inactive/cycles, libraries you've used, etc), and I will start my part immediately.

Meanwhile, you can modify manuscript and revise it carefully. Then, I will include my results in it, review the whole manuscript, and then will ask @katyhuff for review. Also, @katyhuff, hopefully, will help to determine in which journal we can submit it.

Good work!

**Comment by andrewryh** [comment]
@osamamala I started calculating thermal feedback and have few questions about your TCR calculations:
1) Fuel salt density for 900K is 3.3g/cm3 (it is from your and Chinese paper). Did you estimate density change using **Dilatation co-efficiency of fuel (g/(cm3⋅K))** from their paper?
2) Have you changed graphite density or kept it 2.3g/cm3 for all temperatures?
3) Have you changed graphite elements linear dimensions (because they will expand as temperature rise)?
4) Why you used `therm graphiteLib  grj3.00t ` in line 28? This is means using thermal scattering libraries for graphite for temperature **294K**. Have you changed this line when changed the temperature of graphite for TCR calculation?

I got **-0.8pcm/K**, so, trying to understand your and Chinese guys approach...

**Comment by osamamala** [comment]
@andrewryh 

1] Yes, I used the Dilatation co-efficiency of fuel (-6.7E-4) to calculate the change of density for, 
900 ==> 3.3 g/cc
960 ==> 3.26
1015 ==> 3.23
1075 ==> 3.2
1130 ==>3.14
and calculate the TCR using P= (dKeff/keff.dT)*10^5= [pcm/k].

2] kept it constant 2.3 g/cc.

3] I neglected the expansion of the graphite elements.
4] No I didn't change line 28.

**Comment by andrewryh** [comment]
Li paper says:
> The total TCR includes the graphite TCR and the molten salt TCR, and the latter consists of the Doppler effect and the density effect.

So, I am considering separately this 3 factors of thermal feedback:
- Fuel Salt density effect
- Fuel Salt Doppler
- Graphite Doppler

Neglecting graphite density and linear dimensions change (no data for this sort of graphite). For MSBR  Graphite density and thermal expansion effect is about **+0.14pcm/K** for initial and **+0.23pcm/K** for equilibrium compositions.

2.3g/cc is very strength density fo graphite. Crystal density of graphite 2.225 g/cc at 294K. So, for 900K it should be less than 2.225g/cc even if they indent to grow a single crystal for each graphite element.

**Comment by osamamala** [comment]
@andrewryh 
Hi,
Results after thermal scattering data correction ==>
https://github.com/osamamala/saltproc-validation/tree/master/SD-TMSR/doc/plots_60_years_using_SERPENT
output files as usual in this link; 
https://github.com/osamamala/saltproc-validation/tree/master/SD-TMSR/serpent/60-years-analysis

the latest input file will be sent to you by email.
thanks

**Comment by andrewryh** [comment]
@osamamala Looks good to me.
I have done simulations and visualization for initial fuel case. Plots here: https://github.com/arfc/saltproc-validation/tree/master/SD-TMSR/doc/plots_initial_comp_safety_param

The output here: https://github.com/arfc/saltproc-validation/tree/master/SD-TMSR/safety_parameters

The plotter is here: https://github.com/arfc/saltproc-validation/blob/master/SD-TMSR/plotters/SERPENT2_depleted_composition_ploter.ipynb

**Comment by andrewryh** [comment]
Looks good to me.
I finished calculations and visualization for initial composition.
Thanks for input file and output - I can extract equilibrium composition.

How about neutron spectrum for a different time after startup? I need it to
decide composition at which timestep to take. I think initial, 8 years, 10
years and 16 years should be enough.

Thanks.
Andrei

P.S. Are you revising the manuscript? At some point I will create
TeX-template for you, so, you'll be able to transfer your text from Word to
TeX. I also make my section in the TeX, so, you will have an example. All
Elsevier journals nowadays required papers strictly in TeX format using
their template.

**Comment by osamamala** [comment]
@andrewryh 
Looks good to me.
the neutron spectrum for a different time here;
https://github.com/osamamala/saltproc-validation/blob/master/SD-TMSR/doc/plots_60_years_using_SERPENT/spectrum.png

it is enough or should I run 18, 20... etc?

thanks

**Comment by osamamala** [comment]
@andrewryh 
Hi, 
Andrei, please, could you explain how you calculated the reactivity coefficient for Total core. Did you increase the whole reactor temperature from 900K to 1000K? Did you notice that -0.98 is not a high negative temperature coefficient or it is normal for the initial case?

https://github.com/arfc/saltproc-validation/blob/master/SD-TMSR/doc/plots_initial_comp_safety_param/temperature_coeff_init.png

**Comment by andrewryh** [comment]
@osamamala

1) Yes, could you please make it for 20, 40, 60 years? Then we should select 4 most interesting spectra.

2) I ran simulation for 900K everywhere, then for 1000K (I changed fuel density and temperature, graphite temperature and thermal scattering temperature). Robertson for MSBR calculated -0 87pcm/K for initial. So, it is looks realistic. Your and Like coefficient has been obtained without changing thermal scattering cross section library temperature...

Will see what I obtain for equilibrium. I think it will be worse.

**Comment by andrewryh** [comment]
As you can see, graphite Doppler is positive and large. That's why we don't build RBMK anymore...

**Comment by osamamala** [comment]
@andrewryh 
1. Okay, I will.
2. Yes, I see table 5.2 in your thesis the reference value is -0.87 pcm/K.
I agree with you about RBMK.

**Comment by osamamala** [comment]
@andrewryh 

The neutron flux for initial, 20, 22 and 24 years here; 
https://github.com/osamamala/saltproc-validation/blob/master/SD-TMSR/doc/plots_60_years_using_SERPENT/spectrum.png

the spectrum is almost didn't change.
