### ISSUE TITLE
Total mass conservation in the SD-TMSR SERPENT built-in simualtion

### ISSUE THREAD

**Issue by andrewryh** [arfc/saltproc-validation#7]
@osamamala In your manuscript Table 1 says that total fuel salt volume is 52.9m3 and fuel salt density is 3.3g/cm3 (and input for SERPENT agrees with that).
Consequently, we havs 52.9x3.3=**174.57t** fuel salt inventory with should be conserved during 60 years lifetime.

Below plots which I made using your SERPENT output (just took MDENS and multiplied it by total volume=52.9m3):
![total_fuel_salt_mass](https://user-images.githubusercontent.com/20629016/50993450-518d7b80-14df-11e9-8b91-7fc90f721ffb.png)
![u233_mass](https://user-images.githubusercontent.com/20629016/50993496-6ff37700-14df-11e9-8eda-146c737834f4.png)
![th232_mass](https://user-images.githubusercontent.com/20629016/50993550-94e7ea00-14df-11e9-8156-b3f6523bfa24.png)

So, total mass decreasing significantly and U233 and Th232 growing. Total mass should be conserved and we need to figure it out before moving forward.

**Comment by andrewryh** [comment]
I also plotted total mass for MAT: gastank, add, extrafuel to find the source of the discrepancy:

![total_gastank_mass](https://user-images.githubusercontent.com/20629016/50993951-84843f00-14e0-11e9-8765-53285b662a8d.png)
![add_mass](https://user-images.githubusercontent.com/20629016/50994016-b1385680-14e0-11e9-8b5a-aefcd1fef23b.png)
![extrafuel_mass](https://user-images.githubusercontent.com/20629016/50994084-ea70c680-14e0-11e9-8df7-26f0422316fd.png)

**Comment by andrewryh** [comment]
So, you have removed about 105t FPs.
ADD and EXTRAFUEL mass doesn't say much because it was just constant feed.
Input file says 0.4E-7 1/s and ADD volume is 1E+6cm3 or 1m3 (equal 3.3t).
S0, 0.4E-7 x 3.3t = 0.132g/s = 249.8t/60yrs.

So:
loss - 105 t
gain - 250t
and total mass get lost: 80t

I can't understand this and can code it in SaltProc...

**Comment by osamamala** [comment]
@andrewryh I'm trying to figure it out but what you say seems to be right and coincided with the plots.

**Comment by osamamala** [comment]
@andrewryh   did you take into account that the density of adding fuel is 18.95 g/cc?

**Comment by andrewryh** [comment]
Nope, my bad. Then 1m3=18.95t. Hence, 0.4E-7 x 18.95t = 0.758g/s = 1434.26 t/60yrs.
Still doesn't match.

**Comment by andrewryh** [comment]
I uploaded the plotter: https://github.com/arfc/saltproc-validation/blob/master/SD-TMSR/plotters/SERPENT2_depleted_composition_ploter.ipynb

So, you can play with it also

**Comment by andrewryh** [comment]
@osamamala I guess you will repeat simulations to fix this issue. I think it would be nice to change also reprocessing scheme to match with Chinese SCALE paper. Some details from their paper:
**Removals:**
1. **FPs and non-dissolved metals (the atomic number Z = 1, 2, 7, 8,10, 18, 36, 41, 42, 43, 44, 45, 46, 47, 51, 52, 54, 71, 72, 73, 74, 75, 76,77, 78, 79 and 86) via an on-line He gas bubbling system** - removed every **30sec (removal constant 3.333E-2)**
2. **chemical removal of lanthanides and other soluble FPs (Z = 30, 31,32, 33, 34, 35, 37, 38, 39, 40, 48, 49, 50, 53, 55, 56, 57, 58, 59, 60, 61,62, 63, 64, 65, 66, 67, 68, 69, 70) via batch reprocessing by on-suite facility. The removing rates varying from 50 L/d to 5m3/d have been simulated.** I guess you took **5m3/d**, hence, reprocessing cycle time will be 52.9/5  = **10.58 days**
3. **Pa is also extracted by the chemical reprocessing. Its re-processing rate is the same as the chemical reprocessing rate.** - Hence, Pa, reprocessing cycle time =  **10.58 days**

**Feeds**
1. **The extracted 233Pa (with a half-life of 27.3 days) decays into 233U out of the active core, part of which is refueled into the core for criticality and the other (if any is left) is the net 233U production.** - Hence, 233U feed rate is FRACTION of Pa removal rate. They don't mentioned what is this fraction. I guess, it is something you should vary to obtain  1 < Keff 1.03 (for example).
2. **Th232 rate is not specified**. I think Th232 feed rate should be selected to have the total mass of the salt unchanged.

For example, from the plot above for your model you removing 85t of FP over 60years or 0.045g/s. Consequently, U233+Th232 mass rate should compensate this removal = 0.045g/s.

Few recommendations and advises:
1. Separate _gastank_ and _pa_tank_ in your input. Remove Pa in pa_tank and all other stuff in _gastank_. In this case, you will be able to estimate how much Pa you are removing and calculate U233 feed rate.
2. Please, make the table with reprocessing parameters. Examples in my MS thesis and below:
![screenshot from 2019-01-11 08-48-38](https://user-images.githubusercontent.com/20629016/51040677-be575300-157d-11e9-9d80-6fd53965935d.png)

Later I will be able to use parameters from this table to setup SaltProc run and you will include it in any manuscript about your TMSR simulation using SERPENT2.

Thanks.

**Comment by osamamala** [comment]
@andrewryh it is exactly what I started to do! 
thanks

**Comment by osamamala** [comment]
@andrewryh 
please, see;
https://github.com/osamamala/saltproc-validation/tree/master/SD-TMSR/doc/plots_rep_table_for_10_years-analysis
and for output files see;
https://github.com/osamamala/saltproc-validation/tree/master/SD-TMSR/serpent/10-years-analysis

This is 10 years simulation of SD_TMSR with Serpent 2 the reprocessing scheme is illustrated in the rep_table.png in the ../doc.
The total mass is almost conserved during the depletion.
The refill of Th and U233 is also calculated and illustrated in fig. Th232refill.png and U-233refill.png.

waiting for your

**Comment by andrewryh** [comment]
@osamamala Reprocessing table?

**Comment by osamamala** [comment]
https://raw.githubusercontent.com/osamamala/saltproc-validation/master/SD-TMSR/doc/plots_rep_table_for_10_years-analysis/rep_table.png

@andrewryh

**Comment by andrewryh** [comment]
@osamamala May I ask you to play with the reprocessing scheme a little bit more?
Particularly, would be nice to have:

1. Keff not dropping below 1.0 (on the second step it is 0.997908 in your output).
2. Please, try to have Keff as close to 1.0 as possible. It is rising from 1.01 to 1.10 over 10 years. It is not good because:
- it means we have to compensate this excess of reactivity by some control rods (but we don't have control rods which have worth 10'000pcm
- due to high Keff your BR is decreasing quite fast.

So, please, try to keep Keff in range 1.0-1.02 (ideally, 1.0-1.01). I know that it is hard but give it shot.

P.S. I see that mass is conserved now, it is perfect!

**Comment by osamamala** [comment]
@andrewryh 
I can increase the flow rate of U233 of course it will solve the dropping of keff in the second step but also give Keff > 1.10 over the 10 yrs. 

==> What about adding boric acid to compensate this excess of reactivity?

**Comment by andrewryh** [comment]
Yeah, I know. Try piecewise feeds.
You can split your timeline and specify feeds on each.

Boric acid does not suppose to be used in molten salt reactors.

**Comment by osamamala** [comment]
@andrewryh 
please, see;
https://github.com/osamamala/saltproc-validation/tree/master/SD-TMSR/doc/plots_rep_table_for_10_years-analysis/new
for the reprocessing scheme;
https://raw.githubusercontent.com/osamamala/saltproc-validation/master/SD-TMSR/doc/plots_rep_table_for_10_years-analysis/new/table.png
for output files see;
https://github.com/osamamala/saltproc-validation/tree/master/SD-TMSR/serpent/10-years-analysis/new

best

**Comment by andrewryh** [comment]
Looks good for me.
Uncertainty is kinda big (~88pcm), I would try to reach at least 30pcm (in my recent paper we did <16pcm for 60 years).
And total mass changes from 174.9t to 174.25t (0.34%), I usually try to reach total mass fluctuation <0.1%.

But looks really good. @osamamala Are you expecting SaltProc results for the reprocessing table from me at that stage?

**Comment by osamamala** [comment]
@andrewryh 
I will play with the uncertainty and total mass changes trying to polish the results and increase the time up to 60 yrs.
about the SaltProc results, I think it is better to wait a little bit.

**Comment by andrewryh** [comment]
@osamamala Also, please let me give you advice: do not create a new folder (like NEW in 10-years-analysis) to push new results. Just overwrite it. The beauty of GitHub that we always can look back and see the history of changes of the files.
And, please, keep the input file with your output files also, so, anybody would be able to reproduce your results.
Thanks
